apiVersion: v1
kind: ConfigMap
metadata:
  name: fleet-config
data:
  RABBITMQ_URL: amqp://fleet:fleet@rabbitmq:5672/
  QUEUE_NAME: fleet-telemetry
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  MONGO_URI: mongodb://mongodb:27017/
  MONGO_DB: fleet_db
  MONGO_COLLECTION: telemetry_logs
  TELEMETRY_URL: http://ingestion:80/telemetry
